import React from 'react'
import './Research.css'
import missionImage from '../../Assets/researchImage.webp'
import hippocampus from '../../Assets/hippocampus.webp'

export default  function Research() {
  return (
    <div className='research-page'>
        {/* top part of the project */}
        <div className='research-page-top'>
            <div className="research-page-container">
                <div className="research-image">
                    <img src={missionImage} alt="research image" />
                </div>
                <p className='research-text'>RESEARCH</p>
                <p className="research-overview">Overview</p>
                <p>In the Parent Lab our main focus is to understand 
                how brain areas involved in cognition control eating 
                behaviors.
                </p>
                <p>
                Memory of a recently eaten meal can serve as a powerful mechanism 
                for controlling future eating behavior because it likely outlasts
                most physiological signals generated by a meal and regulates 
                homeostatic (i.e., need-based) and hedonic (i.e., 
                pleasure/reward-based) feeding.
                </p>
                <p>
                Our research suggests that hippocampal neurons are critical for 
                forming a memory of a meal and inhibiting future intake, both in 
                terms of delaying the initiation of the next meal and limiting the 
                amount consumed during that next meal. Our findings also suggest 
                that obesity disrupts these processes, thereby causing further 
                overeating and exacerbating the obesity.
                </p>
                <p>
                Our research involves measures of rodent behavior, manipulations 
                of the brain (neuropharmacology, optogenetics and genetics) and 
                molecular and biochemical research strategies (PCR, biochemistry, 
                immunohistochemistry) to measure the impact of ingestion on the 
                brain.
                </p>
            </div>
        </div>
        <div className="current-projects-banner">
            <p>CURRENT PROJECTS</p>
        </div>
        {/* area with all project lists  */}
        <div className="current-projects-list">


                {/* Requires API  */}

            {/* A single project item  */}
            <div className="current-project-item">
                {/* Project's image */}
                <div className="project-image">
                    <img src={hippocampus} alt="hippocampus image" />
                </div>
                {/* Project's name */}
                <div className="project-name">

                </div>
                {/* project's link */}
                <div className="project-link">

                </div>
            </div>



        </div>
    </div>
  )
}
